---
apiVersion: v1
kind: Namespace
metadata:
  name: exo1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo1-web
  namespace: exo1
spec:
  selector:
    matchLabels:
      app: exo1-app
  replicas: 1
  template:
    metadata:
      labels:
        app: exo1-app
    spec:
      containers:
      - name: exo1-container
        image: <docker_id/image:tag>
        imagePullPolicy: Always 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: exo1-svc
  namespace: exo1
spec:
  type: NodePort
    app: exo1-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31201
    protocol: TCP

