---
apiVersion: v1
kind: Namespace
metadata:
  name: exo2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo2-app
  namespace: exo2
spec:
  selector:
    matchLabels:
      app: exo2-app
  replicas: 1
  template:
    metadata:
      labels:
        app: exo2-app
    spec:
      containers:
      - name: vc-webserver-container
        image: <docker_id/image:tag>
        imagePullPolicy: Always 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: exo2-svc
  namespace: exo2
spec:
  type: NodePort
  selector:
    app: exo2-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31202
    protocol: TCP

