apiVersion: apps/v1
kind: Deployment
metadata:
  name: vc-deploy-webserver
  namespace: visitcounter

spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 3

  # template du Pod répliqué
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: vc-webserver-container
        image: opusidea/visitcounter:0.2
        imagePullPolicy: Always # force le re-download (pull) de l'image même si déjà présente dans le cluster
        ports:
        - containerPort: 3000 # le serveur conteneurisé écoute 3000

---

apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: visitcounter

spec:
  type: NodePort # Exposition externe
  selector:
    app: webserver
  ports:
  - port: 3000 # port du service (proxy) pour traffic interne
    targetPort: 3000 # port des pods du déploiement
    nodePort: 31200 # port ouvert pour l'extérieur du cluster
    protocol: TCP

