apiVersion: apps/v1
kind: Deployment
metadata:
  name: vc-deploy-redis
  namespace: visitcounter

spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1

  # template du Pod répliqué
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: vc-redis-container
        image: redis:5-alpine
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis # application web se connectera au nom de service "redis"
  namespace: visitcounter

spec:
  type: ClusterIP # type de service par défaut. Exposition interne au cluster
  selector:
    app: redis
  ports:
  - port: 6379 # port du service (proxy)
    targetPort: 6379 # port des pods du déploiement
    protocol: TCP

